apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: cpanel
  namespace: default
spec:
  acme:
    email: nobody@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cpanel-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.imsenterprises.com
          solverName: cpanel
          config:
            url: "https://cpanel:2087"
            username: "root"
            # Secret needs added ahead of time
            accessKeySecretRef:
              name: "cpanel"
              key: "accessKey"
